server:
  port: 8082
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    open-in-view: true # 合并多个DruidDataSource的监控数据
    hibernate:
      ddl-auto: update   # none | validate | update | create-drop
      spring.jpa.hibernate.naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #默认转换策略
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database: sql_server
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    druid:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName:  com.microsoft.sqlserver.jdbc.SQLServerDriver
        url:  jdbc:sqlserver://192.168.99.26:1433;DatabaseName=oa
        username: sa
        password: stepit
        initialSize:  5   # 下面为连接池的补充设置，应用到上面所有数据源中
        minIdle:  5  # 初始化大小，最小，最大
        maxActive: 20
        maxWait:  60000  # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis:  60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
        validationQuery:  SELECT 1
        testWhileIdle:  true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize:  20
        filters:  stat,log4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

application:
  #版本
  version: 1.0.0
  #文件上传路径
  profile: D:/upload/profile/


